"""baseline schema

Revision ID: 883102153f8d
Revises: 
Create Date: 2026-08-03 15:06:02.434192
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '883102153f8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('topic', sa.String(length=80), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_messages_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_messages_status'), ['status'], unique=False)

    op.create_table('rate_limit_buckets',
    sa.Column('scope', sa.String(length=80), nullable=False),
    sa.Column('subject_hash', sa.String(length=64), nullable=False),
    sa.Column('window_start', sa.BigInteger(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('scope', 'subject_hash', 'window_start')
    )
    with op.batch_alter_table('rate_limit_buckets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limit_buckets_expires_at'), ['expires_at'], unique=False)

    op.create_table('techniques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('required_plan', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('plan', sa.String(), nullable=True),
    sa.Column('subscription_status', sa.String(), nullable=True),
    sa.Column('paypal_subscription_id', sa.String(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_ends_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('body_calibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ratios_json', sa.Text(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('stability_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('body_calibrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_calibrations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_calibrations_user_id'), ['user_id'], unique=True)

    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('practice_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('technique_id', sa.Integer(), nullable=True),
    sa.Column('technique_name', sa.String(), nullable=True),
    sa.Column('step_key', sa.String(), nullable=True),
    sa.Column('step_name', sa.String(), nullable=True),
    sa.Column('target_reps', sa.Integer(), nullable=True),
    sa.Column('completed_reps', sa.Integer(), nullable=True),
    sa.Column('clean_reps', sa.Integer(), nullable=True),
    sa.Column('average_accuracy', sa.Float(), nullable=True),
    sa.Column('best_accuracy', sa.Float(), nullable=True),
    sa.Column('average_rep_seconds', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['technique_id'], ['techniques.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_sessions_step_key'), ['step_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_sessions_technique_id'), ['technique_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_sessions_technique_name'), ['technique_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('replaced_by_hash', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_sessions_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_sessions_revoked_at'), ['revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('technique_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.Integer(), nullable=True),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('step_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['technique_id'], ['techniques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temporal_labeling_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('technique_key', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('temporal_labeling_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temporal_labeling_drafts_admin_user_id'), ['admin_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_temporal_labeling_drafts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_temporal_labeling_drafts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_temporal_labeling_drafts_technique_key'), ['technique_key'], unique=False)

    op.create_table('training_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('technique_id', sa.Integer(), nullable=True),
    sa.Column('technique_name', sa.String(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_accuracy', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['technique_id'], ['techniques.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_sessions_technique_id'), ['technique_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_sessions_technique_name'), ['technique_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('user_training_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('memory_key', sa.String(), nullable=True),
    sa.Column('memory_value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_training_memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_training_memory_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_training_memory_memory_key'), ['memory_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_training_memory_user_id'), ['user_id'], unique=False)

    op.create_table('practice_reps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_session_id', sa.Integer(), nullable=True),
    sa.Column('rep_number', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('speed_label', sa.String(), nullable=True),
    sa.Column('quality_label', sa.String(), nullable=True),
    sa.Column('focus_body_part', sa.String(), nullable=True),
    sa.Column('issue', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_reps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_reps_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_reps_practice_session_id'), ['practice_session_id'], unique=False)

    op.create_table('practice_session_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_session_id', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_session_analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_session_analytics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_session_analytics_practice_session_id'), ['practice_session_id'], unique=True)

    op.create_table('practice_session_tapes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practice_session_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('frame_rate', sa.Integer(), nullable=True),
    sa.Column('frame_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('codec', sa.String(), nullable=True),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('uncompressed_bytes', sa.Integer(), nullable=True),
    sa.Column('compressed_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['practice_session_id'], ['practice_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_session_tapes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_session_tapes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_session_tapes_practice_session_id'), ['practice_session_id'], unique=True)

    op.create_table('target_angles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('body_part', sa.String(), nullable=True),
    sa.Column('min_angle', sa.Float(), nullable=True),
    sa.Column('max_angle', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['step_id'], ['technique_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_feedback_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('step_key', sa.String(), nullable=True),
    sa.Column('body_part', sa.String(), nullable=True),
    sa.Column('issue', sa.String(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_feedback_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_feedback_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_feedback_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_feedback_events_step_key'), ['step_key'], unique=False)

    op.create_table('training_step_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('step_key', sa.String(), nullable=True),
    sa.Column('step_name', sa.String(), nullable=True),
    sa.Column('best_accuracy', sa.Float(), nullable=True),
    sa.Column('average_accuracy', sa.Float(), nullable=True),
    sa.Column('attempts_count', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_step_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_step_attempts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_step_attempts_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_step_attempts_step_key'), ['step_key'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_step_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_step_attempts_step_key'))
        batch_op.drop_index(batch_op.f('ix_training_step_attempts_session_id'))
        batch_op.drop_index(batch_op.f('ix_training_step_attempts_id'))

    op.drop_table('training_step_attempts')
    with op.batch_alter_table('training_feedback_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_feedback_events_step_key'))
        batch_op.drop_index(batch_op.f('ix_training_feedback_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_training_feedback_events_id'))

    op.drop_table('training_feedback_events')
    op.drop_table('target_angles')
    with op.batch_alter_table('practice_session_tapes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_session_tapes_practice_session_id'))
        batch_op.drop_index(batch_op.f('ix_practice_session_tapes_id'))

    op.drop_table('practice_session_tapes')
    with op.batch_alter_table('practice_session_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_session_analytics_practice_session_id'))
        batch_op.drop_index(batch_op.f('ix_practice_session_analytics_id'))

    op.drop_table('practice_session_analytics')
    with op.batch_alter_table('practice_reps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_reps_practice_session_id'))
        batch_op.drop_index(batch_op.f('ix_practice_reps_id'))

    op.drop_table('practice_reps')
    with op.batch_alter_table('user_training_memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_training_memory_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_training_memory_memory_key'))
        batch_op.drop_index(batch_op.f('ix_user_training_memory_id'))

    op.drop_table('user_training_memory')
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_training_sessions_technique_name'))
        batch_op.drop_index(batch_op.f('ix_training_sessions_technique_id'))
        batch_op.drop_index(batch_op.f('ix_training_sessions_id'))

    op.drop_table('training_sessions')
    with op.batch_alter_table('temporal_labeling_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temporal_labeling_drafts_technique_key'))
        batch_op.drop_index(batch_op.f('ix_temporal_labeling_drafts_status'))
        batch_op.drop_index(batch_op.f('ix_temporal_labeling_drafts_id'))
        batch_op.drop_index(batch_op.f('ix_temporal_labeling_drafts_admin_user_id'))

    op.drop_table('temporal_labeling_drafts')
    op.drop_table('technique_steps')
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_revoked_at'))
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_family_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_expires_at'))

    op.drop_table('refresh_sessions')
    with op.batch_alter_table('practice_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_practice_sessions_technique_name'))
        batch_op.drop_index(batch_op.f('ix_practice_sessions_technique_id'))
        batch_op.drop_index(batch_op.f('ix_practice_sessions_step_key'))
        batch_op.drop_index(batch_op.f('ix_practice_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_practice_sessions_id'))

    op.drop_table('practice_sessions')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_expires_at'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('body_calibrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_calibrations_user_id'))
        batch_op.drop_index(batch_op.f('ix_body_calibrations_id'))

    op.drop_table('body_calibrations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('techniques')
    with op.batch_alter_table('rate_limit_buckets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_limit_buckets_expires_at'))

    op.drop_table('rate_limit_buckets')
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_messages_status'))
        batch_op.drop_index(batch_op.f('ix_contact_messages_id'))
        batch_op.drop_index(batch_op.f('ix_contact_messages_email'))
        batch_op.drop_index(batch_op.f('ix_contact_messages_created_at'))

    op.drop_table('contact_messages')
    # ### end Alembic commands ###
