import fs from "node:fs/promises";
import path from "node:path";
import { SpreadsheetFile, Workbook } from "@oai/artifact-tool";

const outputDir = path.resolve("research/outputs/literature/20260801");
await fs.mkdir(outputDir, { recursive: true });

const rows = [
  ["S01","Bazarevsky et al.",2020,"BlazePose: On-device Real-time Body Pose Tracking","arXiv preprint","Perception / pose","Single RGB image/video","33 body keypoints; lightweight on-device pose pipeline","Speed and pose quality comparisons","Supports the feasibility of real-time, laptop-camera body landmark extraction.","General pose benchmarks do not establish jab-angle or coaching accuracy.","Justifies the implemented MediaPipe landmark layer, not downstream correctness.","Architecture; limitations","10.48550/arXiv.2006.10204","https://arxiv.org/abs/2006.10204","Official metadata and abstract verified","Include"],
  ["S02","Grishchenko et al.",2022,"BlazePose GHUM Holistic: Real-time 3D Human Landmarks and Pose Estimation","arXiv preprint","Perception / holistic landmarks","Monocular RGB","Lightweight monocular 3D body and hand landmark estimation","Benchmark quality and runtime","Supports integrated body/hand landmark tracking from one camera.","Monocular depth and occlusion remain ambiguous; coordinates are not calibrated biomechanics.","Supports body/hand sensing scope and explicit measurement limitations.","Architecture; limitations","10.48550/arXiv.2206.11678","https://arxiv.org/abs/2206.11678","Official metadata and abstract verified","Include"],
  ["S03","Zhang et al.",2020,"MediaPipe Hands: On-device Real-time Hand Tracking","arXiv preprint","Perception / hands","RGB images/video","Palm detection plus 21-landmark hand model","Tracking quality and runtime","Supports real-time hand landmark tracking used in hand diagnostics.","Hand tracking alone does not validate guard quality or martial-arts form.","Justifies the hand layer while bounding coaching claims.","Architecture; limitations","10.48550/arXiv.2006.10214","https://arxiv.org/abs/2006.10214","Official metadata and abstract verified","Include"],
  ["S04","Lugaresi et al.",2019,"MediaPipe: A Framework for Building Perception Pipelines","arXiv preprint","Perception systems","Cross-platform perception applications","Graph-based pipelines for multimodal perception","Runtime/deployment examples","Supports a modular, real-time perception-pipeline architecture.","Framework capability is not evidence that a particular application is accurate.","Supports modular sensor-to-landmark pipeline design.","Architecture","10.48550/arXiv.1906.08172","https://arxiv.org/abs/1906.08172","Official metadata and abstract verified","Include"],
  ["S05","Yan, Xiong & Lin",2018,"Spatial Temporal Graph Convolutional Networks for Skeleton-Based Action Recognition","AAAI Conference on Artificial Intelligence 32(1)","Skeleton graph learning","Skeleton action datasets","Spatiotemporal graph convolution over joints and temporal edges","Action-recognition accuracy","Establishes skeleton sequences as spatiotemporal graphs for learned action representation.","Action recognition differs from future-pose regression and single-jab phase inference.","Foundational rationale for graph-based skeleton modelling.","Related work; model rationale","10.1609/aaai.v32i1.12328","https://ojs.aaai.org/index.php/aaai/article/view/12328","Official metadata and abstract verified","Include"],
  ["S06","Shi et al.",2019,"Two-Stream Adaptive Graph Convolutional Networks for Skeleton-Based Action Recognition","CVPR","Skeleton graph learning","NTU-RGB+D; Kinetics-Skeleton","Adaptive graph topology with joint and bone streams","Action-recognition accuracy","Shows that learned topology and bone vectors can improve skeleton-action models.","Large recognition benchmarks and depth-derived skeletons do not match the P001 webcam case.","Supports adaptive spatial relations and bone-aware features as design precedents.","Related work; model rationale","","https://openaccess.thecvf.com/content_CVPR_2019/html/Shi_Two-Stream_Adaptive_Graph_Convolutional_Networks_for_Skeleton-Based_Action_Recognition_CVPR_2019_paper.html","Official full paper and metadata available; abstract verified","Include"],
  ["S07","Chen et al.",2021,"Multi-Scale Spatial Temporal Graph Convolutional Network for Skeleton-Based Action Recognition","AAAI Conference on Artificial Intelligence 35(2)","Skeleton graph learning","Skeleton action-recognition datasets","Multi-scale spatial-temporal graph convolution","Action-recognition accuracy","Motivates multi-scale joint relations and temporal receptive fields.","Recognition results cannot be transferred directly to phase classification or anticipation.","Related precedent for L2 skeletal action representation.","Related work","10.1609/aaai.v35i2.16197","https://ojs.aaai.org/index.php/AAAI/article/view/16197","Official metadata and abstract verified","Include"],
  ["S08","Martinez, Black & Romero",2017,"On Human Motion Prediction Using Recurrent Neural Networks","CVPR","Human motion prediction","Human3.6M","Sequence-to-sequence recurrent baseline and residual prediction","Joint-angle prediction error across horizons","Shows that a simple zero-velocity/last-pose baseline can be difficult to beat at short horizons.","Benchmark motions and joint-angle protocols differ from normalized MediaPipe jab landmarks.","Requires ACP-STGAT comparisons against simple baselines and horizon-specific reporting.","Model evaluation","","https://openaccess.thecvf.com/content_cvpr_2017/html/Martinez_On_Human_Motion_CVPR_2017_paper.html","Official full paper and metadata available; abstract verified","Include"],
  ["S09","Mao et al.",2019,"Learning Trajectory Dependencies for Human Motion Prediction","ICCV","Human motion prediction","Human3.6M; CMU Mocap; 3DPW","DCT trajectory representation with learned graph dependencies","Motion-prediction error across horizons","Supports modelling temporal trajectories together with learned spatial joint dependencies.","Public mocap benchmarks do not establish monocular jab performance.","Direct precedent for ACP-STGAT temporal/spatial dependency rationale.","Related work; model rationale","","https://openaccess.thecvf.com/content_ICCV_2019/html/Mao_Learning_Trajectory_Dependencies_for_Human_Motion_Prediction_ICCV_2019_paper.html","Official full paper and metadata available; abstract verified","Include"],
  ["S10","Li et al.",2019,"Actional-Structural Graph Convolutional Networks for Skeleton-Based Action Recognition","CVPR","Skeleton graphs / prediction auxiliary task","NTU-RGB+D; Kinetics","Actional and structural graph links plus future-pose auxiliary head","Recognition accuracy; future-pose diagnostic","Shows future-pose prediction can regularize detailed skeletal action representation.","Prediction is auxiliary and the task is recognition, not coaching anticipation.","Connects skeletal action representation with future-pose modelling.","Related work","","https://openaccess.thecvf.com/content_CVPR_2019/html/Li_Actional-Structural_Graph_Convolutional_Networks_for_Skeleton-Based_Action_Recognition_CVPR_2019_paper.html","Official full paper and metadata available; abstract verified","Include"],
  ["S11","Abu Farha & Gall",2019,"MS-TCN: Multi-Stage Temporal Convolutional Network for Action Segmentation","CVPR","Temporal action segmentation","50Salads; Georgia Tech Egocentric Activities; Breakfast","Multi-stage dilated temporal convolution with smoothing loss","Frame accuracy; edit score; segmental F1","Directly addresses framewise action segmentation and over-segmentation.","Long multi-action videos differ from short ordered jab phases.","Supports temporal refinement and the need for boundary/sequence metrics beyond accuracy.","Phase model; evaluation","","https://openaccess.thecvf.com/content_CVPR_2019/html/Abu_Farha_MS-TCN_Multi-Stage_Temporal_Convolutional_Network_for_Action_Segmentation_CVPR_2019_paper.html","Official full paper and metadata available; abstract verified","Include"],
  ["S12","Yi, Wen & Jiang",2021,"ASFormer: Transformer for Action Segmentation","BMVC","Temporal action segmentation","Three public action-segmentation datasets","Local-connectivity transformer with hierarchical temporal representation and iterative decoder","Frame/segment action-segmentation metrics","Shows local temporal priors and decoder refinement can help with long sequences and small datasets.","Still assumes substantially larger labelled datasets than the current generated bootstrap set.","Alternative temporal architecture and small-data caution.","Phase model; future work","10.48550/arXiv.2110.08568","https://arxiv.org/abs/2110.08568","Official preprint metadata and abstract verified","Include"],
  ["S13","Ionescu et al.",2014,"Human3.6M: Large Scale Datasets and Predictive Methods for 3D Human Sensing in Natural Environments","IEEE TPAMI 36(7)","3D pose dataset","Human3.6M","Synchronized multiview RGB, motion capture, depth and body scans","3D pose estimation baselines","Introduces the controlled Human3.6M benchmark widely used by motion-prediction studies.","Indoor acted activities, calibrated capture and limited actors differ from laptop-camera jab capture.","Supports benchmark provenance and domain-gap disclosure.","Datasets; limitations","10.1109/TPAMI.2013.248","https://vision.imar.ro/human3.6m/human36m_techrep.pdf","Official metadata and full paper available","Include"],
  ["S14","Mehta et al.",2017,"Monocular 3D Human Pose Estimation in the Wild Using Improved CNN Supervision","3DV","Monocular 3D pose","MPI-INF-3DHP","Monocular 3D pose with mixed indoor/outdoor benchmark","3D pose estimation error","Introduces an in-the-wild-oriented benchmark relevant to monocular robustness.","Pose estimation is not temporal prediction; capture conditions still differ from the P001 application.","Supports external pose-data rationale and deployment-domain caveat.","Datasets; limitations","10.1109/3DV.2017.00064","https://arxiv.org/abs/1611.09813","Paper metadata and abstract verified","Include"],
  ["S15","von Marcard et al.",2018,"Recovering Accurate 3D Human Pose in the Wild Using IMUs and a Moving Camera","ECCV","In-the-wild 3D pose dataset","3DPW; more than 51,000 frames","Video plus inertial sensing for accurate ground truth","3D pose estimation evaluation","Demonstrates how inertial sensing can strengthen in-the-wild pose ground truth.","Requires sensors absent from the current laptop-camera-only feasibility case.","Supports sensor-fusion future work and explains current ground-truth limits.","Datasets; future work","","https://openaccess.thecvf.com/content_ECCV_2018/html/Timo_von_Marcard_Recovering_Accurate_3D_ECCV_2018_paper.html","Official full paper and metadata available; abstract verified","Include"],
  ["S16","Wehrbein et al.",2021,"Probabilistic Monocular 3D Human Pose Estimation With Normalizing Flows","ICCV","Monocular 3D pose uncertainty","Human3.6M; MPI-INF-3DHP","Probabilistic pose estimation for ambiguous image evidence","3D pose error and plausibility","Treats monocular 3D pose as ambiguous rather than uniquely observable.","Does not directly evaluate coaching decisions or landmark tracking in this system.","Supports uncertainty-aware interpretation of camera-derived angles and depth.","Limitations; future work","","https://openaccess.thecvf.com/content/ICCV2021/html/Wehrbein_Probabilistic_Monocular_3D_Human_Pose_Estimation_With_Normalizing_Flows_ICCV_2021_paper.html","Official full paper and metadata available; abstract verified","Include"],
  ["S17","Endsley",1995,"Toward a Theory of Situation Awareness in Dynamic Systems","Human Factors 37(1)","Situation awareness","Conceptual and empirical human-factors literature","Three-level situation-awareness model: perception, comprehension, projection","Conceptual validation and human-performance evidence","Defines situation awareness as perception, comprehension and projection, influenced by goals, mental models and attention limits.","A human cognitive theory cannot by itself prove machine cognition or awareness.","Provides a bounded conceptual lens for L1-L4 state and projection; terminology must remain computational.","Conceptual framework; claim control","10.1518/001872095779049543","https://journals.sagepub.com/doi/10.1518/001872095779049543","Publisher metadata and abstract verified","Include"],
  ["S18","Hevner et al.",2004,"Design Science in Information Systems Research","MIS Quarterly 28(1)","Research methodology","Information-systems design research","Design-science framework and guidelines","Artifact utility, quality and efficacy evaluation","Supports evaluation of a designed artifact through relevance, rigor and iterative assessment.","Does not replace empirical validation or resolve researcher self-evaluation bias.","Methodological basis for expert-informed design science and framework evaluation.","Methodology","10.2307/25148625","https://www.jstor.org/stable/25148625","Bibliographic metadata and abstract/summary verified","Include"],
  ["S19","Piorkowski, Lees & Barton",2011,"Single maximal versus combination punch kinematics","Sports Biomechanics 10(1)","Boxing biomechanics","Experienced boxers performing jab, cross and hooks","Punch-type and modality kinematic comparison","Punch speed and delivery time","Shows punch type and execution context affect speed and delivery-time measurements.","Maximal bag punches and group measurements differ from webcam-based self-practice.","Supports jab-specific scope and cautions against generalizing across punch types or contexts.","Domain rationale; limitations","10.1080/14763141.2010.547590","https://www.tandfonline.com/doi/abs/10.1080/14763141.2010.547590","Publisher metadata and abstract verified","Include"],
  ["S20","Lockwood & Tant",1997,"Mechanical and Electromyographical Analysis of a Boxer's Jab","ISBS Conference Proceedings","Jab biomechanics","Four professional and five amateur boxers","2D kinematics, EMG and instrumented bag force","Kinematics, muscle activity and force","Treats the jab as coordinated upper- and lower-body action rather than an isolated elbow movement.","Small sample, older 2D/30 Hz capture and conference evidence limit precision and generalization.","Supports multi-joint feedback priorities while requiring modest biomechanical claims.","Domain rationale; limitations","","https://ojs.ub.uni-konstanz.de/cpa/article/view/3649","Proceedings page and abstract verified","Include with caution"],
  ["S21","Ald'ily et al.",2023,"The Kinematic Analysis of the Straight Punch in Two Ways for Amateur Boxing Players in Jordan","SPORT TK-EuroAmerican Journal of Sport Sciences","Boxing biomechanics","Amateur boxing players","Kinematic comparison of two straight-punch methods","Foot distance, arm movement, speed, time and joint angles","Identifies shoulder, elbow, pelvis and lower-limb angles as relevant straight-punch variables.","Straight-punch methods and study setting may not map exactly to this system's lead jab definition.","Supports multi-joint measurement categories, not fixed universal thresholds.","Domain rationale; limitations","10.6018/sportk.517831","https://revistas.um.es/sportk/article/view/517831","Journal metadata and abstract verified","Include with caution"],
  ["S22","Huang et al.",2019,"STGAT: Modeling Spatial-Temporal Interactions for Human Trajectory Prediction","ICCV","Pedestrian trajectory prediction","Pedestrian trajectory datasets","Spatial-temporal graph attention for person trajectories","Trajectory displacement metrics","Relevant only as a general graph-attention precedent.","Predicts pedestrian paths, not articulated skeletal pose; name overlap with ACP-STGAT can mislead.","Do not use as direct evidence for skeletal future-pose validity; retain as exclusion/terminology note.","Exclusion log","","https://openaccess.thecvf.com/content_ICCV_2019/html/Huang_STGAT_Modeling_Spatial-Temporal_Interactions_for_Human_Trajectory_Prediction_ICCV_2019_paper.html","Official full paper and metadata available; abstract verified","Exclude from direct support"]
];

const headers = ["source_id","authors","year","title","venue","research_area","dataset_or_participants","method_or_concept","metrics_or_evaluation","key_supported_claim","important_limitation","framework_relevance","planned_section","doi","primary_url","verification_level","inclusion_status"];

const fullyExtracted = new Set(["S01","S02","S03","S04","S05","S06","S07","S08","S09","S10","S11","S12","S13","S14","S15","S16","S17","S18","S19","S20","S21"]);
for (const row of rows) if (fullyExtracted.has(row[0])) row[15] = "Full-text analytic extraction completed for selected claims";

const extractionHeaders = ["extract_id","source_id","printed_page_or_section","evidence_type","paraphrased_evidence","method_or_sample_detail","source_limit","defensible_framework_use","local_evidence_required","full_text_url"];
const extractionRows = [
 ["E01","S01","p. 1, Abstract and §2.1","Architecture","BlazePose produces 33 body keypoints for a single person and uses a detector-tracker pipeline for real-time operation.","Single-person pose detector followed by tracker; detector is rerun when presence is lost.","The tracker assumes a single-person use case and pose quality is task/domain dependent.","Support laptop-camera landmark feasibility and the 33-landmark topology.","Application tracking diagnostics and failure cases.","https://arxiv.org/pdf/2006.10204"],
 ["E02","S01","pp. 2–3, §2.4 and §3","Evaluation/limitation","Training included common and fitness poses with simulated occlusion; evaluation used PCK@0.2 on 17 shared COCO points.","60,000 common-pose images plus 25,000 fitness images; two 1,000-image in-house evaluation sets.","PCK@0.2 on 2D points is not jab-form accuracy and does not validate all 33 landmarks equally.","Justify perception choice while explicitly separating vendor pose evaluation from framework evaluation.","P001 visibility/tracking evidence and selected-frame expert review.","https://arxiv.org/pdf/2006.10204"],
 ["E03","S02","p. 1, Abstract and Introduction","Architecture","GHUM Holistic estimates body and hand landmarks from one RGB image and targets on-device laptop/browser operation.","One feed-forward body/hand pipeline plus GHUM lifting; reported 15 FPS on modern phones/browsers.","Reported deployment speed is not this application's measured latency.","Support sensor constraints and holistic landmark architecture.","Local browser/runtime latency and device configuration.","https://arxiv.org/pdf/2206.11678"],
 ["E04","S02","p. 2, §2","Measurement limitation","A given 2D annotation may correspond to several realistic 3D poses with different depth; depth-order annotations were introduced to reduce ambiguity.","GHUM fitting to diverse 2D data; relative metric coordinates centred at the hips.","Model-relative coordinates must not be treated as independently calibrated biomechanics.","Support explicit monocular-depth uncertainty and cautious interpretation of angles/z coordinates.","Calibration study or external sensors before physical-unit claims.","https://arxiv.org/pdf/2206.11678"],
 ["E05","S03","p. 2, hand landmark model","Architecture/limitation","The hand model predicts 21 landmarks with x, y and wrist-relative depth, hand presence and handedness.","Real and synthetic data train 2D coordinates; wrist-relative depth is learned only from synthetic images.","Synthetic depth supervision and occlusion limit direct claims about guard correctness.","Support hand diagnostic visualization, not independent guard validation.","P001 hand-tracking failures and expert-labelled guard frames.","https://arxiv.org/pdf/2006.10214"],
 ["E06","S05","pp. 1–2, Introduction and §3","Model rationale","ST-GCN represents each joint as a node, anatomical links as spatial edges, and same-joint cross-frame links as temporal edges.","Action recognition on skeleton sequences; hierarchical graph convolution integrates spatial and temporal information.","The evaluated task is action recognition, not future-pose regression or ordered jab-phase classification.","Provide foundational graph representation rationale only.","ACP-STGAT ablations/baselines on its own target and data.","https://arxiv.org/pdf/1801.07455"],
 ["E07","S06","pp. 1–2 and p. 8","Model rationale","2s-AGCN learns graph topology and fuses joint coordinates with bone lengths/directions; its two-stream model exceeded either stream alone in its validation setting.","NTU-RGBD and Kinetics-Skeleton action-recognition experiments; joint-stream 93.7%, bone-stream 93.2%, fused 95.1% in the reported ablation.","Large action-recognition datasets, sensor skeletons and labels differ from webcam jab prediction.","Support adaptive relations and bone-aware feature rationale, not transferred accuracy.","Compare ACP-STGAT against fixed/simple alternatives and report jab-specific errors.","https://arxiv.org/pdf/1805.07694"],
 ["E08","S08","pp. 1–2, Introduction","Evaluation control","A constant-pose predictor can outperform more complex recurrent approaches for short-term prediction, exposing weak evaluation baselines and first-frame discontinuities.","Human3.6M short-term motion prediction; quantitative angle-space error and qualitative long-horizon assessment.","Motion-capture joint angles and activities are not normalized MediaPipe jab landmarks.","Require a last-observation/zero-velocity baseline and horizon-wise errors for ACP-STGAT.","Run and preserve baseline metrics on exactly the same evaluation split.","https://arxiv.org/pdf/1705.02445"],
 ["E09","S08","pp. 4–5, §3.2–§4","Model/evaluation","Residual prediction models velocity-like changes and improves continuity between observed and predicted frames.","Sequence-to-sequence GRU decoder consumes its own samples; residual connection adds predicted change to input.","Short-horizon optimisation does not establish long-horizon plausibility or martial-arts anticipation.","Support continuity and displacement-oriented diagnostics.","Per-horizon ADE/FDE, first-frame jump and qualitative failure review.","https://arxiv.org/pdf/1705.02445"],
 ["E10","S11","pp. 3–4, §3.3 and evaluation","Metric selection","MS-TCN combines frame classification with temporal smoothing to reduce over-segmentation and evaluates segmental F1/edit score in addition to frame accuracy.","Multi-stage dilated temporal convolutions; truncated MSE over adjacent log probabilities.","Excess smoothing can damage true action boundaries; hyperparameters affect boundary behaviour.","Support phase boundary, sequence, edit and segmental metrics beyond accuracy.","Human-labelled jab phases and boundary-error computation; generated labels remain pipeline checks.","https://arxiv.org/pdf/1903.01945"],
 ["E11","S11","p. 6, §4.4","Limitation","Increasing smoothing penalties can suppress valid label changes and degrade detected action boundaries.","Ablation varied smoothing weight and truncation threshold.","The optimal values are dataset-specific and cannot be copied to jab phases without validation.","Justify inspecting decoder transitions and boundary failures.","Tune only on grouped training/validation sessions and leave test sessions untouched.","https://arxiv.org/pdf/1903.01945"],
 ["E12","S17","pp. 35–37, definition/model","Conceptual framework","Situation awareness is structured as perception of elements, comprehension of their meaning and projection of near-future status.","Human-factors theory for dynamic human decision making; attention, working memory, goals and mental models are relevant factors.","A theory of human operators does not prove machine consciousness, cognition or equivalence.","Use the three levels as a bounded computational organization for sensed state, interpreted state and prediction.","Component-level evidence for each implemented level; retain non-human-equivalence wording.","https://frankritter.com/ist521/papers/endsley95.pdf"],
 ["E13","S17","Abstract and model discussion","Claim limitation","Situation awareness can be limited by attention/working memory and affected by workload, stress, complexity, automation and interface design.","Theoretical synthesis and error taxonomy across dynamic domains.","These human limitations cannot be directly attributed to the software without operational definitions and tests.","Motivate failure-mode categories and interface/context-selection questions only.","System-specific logging showing missing, misinterpreted or incorrectly projected state.","https://journals.sagepub.com/doi/10.1518/001872095779049543"],
 ["E14","S18","pp. 75–76 and 82–83","Methodology","Design science obtains knowledge through building and applying purposeful artifacts and requires relevance, rigor and evaluation.","Conceptual framework plus seven guidelines for IS design-science research.","Building software alone is routine design unless a research contribution and rigorous evaluation are demonstrated.","Support artifact-centred methodology and the evidence register.","Demonstrate utility, quality, limitations, reproducibility and relation to prior knowledge.","https://www.researchgate.net/publication/201168946_Design_Science_in_Information_Systems_Research"],
 ["E15","S18","pp. 85–86 and 91","Evaluation standard","Artifact evaluation should demonstrate utility, quality and efficacy using appropriate methods; the central questions concern what utility exists and what evidence demonstrates it.","Evaluation methods may include observational, analytical, experimental, testing and descriptive approaches.","A single expert feasibility case cannot establish general utility or effectiveness.","Organize software tests, model checks, P001 case evidence and failure modes as distinct evaluation layers.","Future participants, independent experts and controlled conditions for broader claims.","https://www.researchgate.net/publication/201168946_Design_Science_in_Information_Systems_Research"],
 ["E16","S19","article pp. 1–4, Abstract and Methods","Domain evidence","Punch speed and delivery time depend on punch type and whether punches are performed singly or in combinations.","Ten competition-standard orthodox boxers; eight-camera 3D motion capture; strike dummy; jab, cross and hooks.","Instrumented group laboratory results are not directly transferable to one-person webcam practice.","Support jab-only scoping and context-dependent coaching thresholds.","Do not compare P001 normalized landmark velocities directly with laboratory m/s.","https://clok.uclan.ac.uk/3757/1/piorkowski-et-al-2011-punch-kinematics.pdf"],
 ["E17","S19","article pp. 9–15, Results/Discussion","Domain evidence","Straight punches were characterised by forward trajectories and elbow extension; contact speed correlated with peak elbow-extension velocity, while preparation and guard movement provided early cues.","3D trajectories, angular velocities, contact events and force-platform data.","Correlation was modest and does not define a universal correct elbow-angle threshold or causal coaching rule.","Support monitoring elbow extension, guard displacement and preparation/recovery as multi-joint features.","Expert annotation of selected P001 frames and explicit rule-threshold provenance.","https://clok.uclan.ac.uk/3757/1/piorkowski-et-al-2011-punch-kinematics.pdf"],
 ["E18","S04","pp. 1–2, Abstract and §3","Architecture","MediaPipe defines a perception application as a directed graph of modular calculators connected by timestamped streams and permits components to be inserted or replaced incrementally.","Cross-platform sensory-data framework with immutable packets, typed calculator contracts and reusable subgraphs.","Framework modularity does not prove the correctness of the models or application logic placed in the graph.","Support the modular video-to-landmark perception architecture and replaceable processing stages.","Repository-level component mapping and application-specific verification.","https://arxiv.org/pdf/1906.08172"],
 ["E19","S04","pp. 4–5, §4.1","Runtime/limitation","Timestamp synchronization, deterministic input policies and explicit flow control govern how streaming inputs are aligned or dropped under real-time constraints.","Default policy processes matching timestamps in order without drops; alternative flow-limiter nodes may drop upstream packets.","Real-time flow-control decisions can change the observed sequence and must be measured in the deployed application.","Support timestamp, dropped-frame and end-to-end latency logging requirements.","Local capture FPS, queue/drop events, component and end-to-end latency.","https://arxiv.org/pdf/1906.08172"],
 ["E20","S07","pp. 1–2, Introduction","Model rationale","MST-GCN enlarges spatial and temporal receptive fields through hierarchical multi-scale subgraph convolutions intended to capture both local and distant joint/frame dependencies.","Skeleton action recognition using MS-GC and MT-GC modules stacked in a graph-convolutional network.","The evidence is action-recognition performance on large benchmarks, not future-pose or jab-phase accuracy.","Support multi-scale context as a related architectural precedent only.","Ablation or comparison showing whether multi-scale context helps the implemented jab task.","https://arxiv.org/pdf/2206.13028"],
 ["E21","S07","pp. 5–7, Experiments","Evaluation boundary","Ablations compare spatial, temporal and combined multi-scale modules on NTU RGB+D; the combined model improves its adaptive ST-GCN baseline in that setting.","NTU RGB+D, NTU-120 and Kinetics-Skeleton; action-recognition top-1/top-5 metrics.","Sensor-derived skeleton datasets, many participants and action labels differ materially from P001 MediaPipe landmarks.","Use only to motivate explicit component ablations and parameter-matched baselines.","Equivalent-compute baseline and grouped real-jab evaluation.","https://arxiv.org/pdf/2206.13028"],
 ["E22","S09","pp. 1–4, §3","Model rationale","Mao et al. encode joint trajectories with DCT coefficients and learn graph connectivity instead of restricting spatial dependencies to the kinematic tree.","Feed-forward residual prediction in frequency space; trainable weighted adjacency between joint trajectories.","DCT truncation favours smooth motion and may suppress rapid or high-frequency jab detail.","Support trajectory-space and learned-joint-dependency rationale while motivating high-speed-motion checks.","Per-horizon and peak-velocity/error analysis on jab sequences.","https://arxiv.org/pdf/1908.05436"],
 ["E23","S09","pp. 5 and 9, §4 and supplement","Evaluation","The study evaluates zero-velocity and learned baselines using angle error and MPJPE on Human3.6M, CMU Mocap and 3DPW with participant-level benchmark splits.","Human3.6M tests subject 5; validation uses subject 11; 3DPW uses official splits.","Millimetre MPJPE is valid for calibrated 3D benchmark coordinates, not normalized webcam landmarks.","Support baseline comparisons, participant/session grouping and coordinate-aware metric units.","Retain normalized units for current ACP results and run the last-pose baseline.","https://arxiv.org/pdf/1908.05436"],
 ["E24","S10","pp. 1–3, Introduction and §4.1","Model rationale","AS-GCN combines physical/higher-order structural links with learned action-specific links between potentially distant joints.","Encoder-decoder A-link inference module plus actional-structural graph and temporal convolutions.","Learned links are task/data dependent and are not biomechanical causal relationships.","Support learned non-local dependencies as a computational representation, not biological explanation.","Visualize or ablate learned relations on jab data before interpreting them.","https://arxiv.org/pdf/1904.12659"],
 ["E25","S10","pp. 1–2 and 8, prediction head","Evaluation boundary","A future-pose head is used as an auxiliary self-supervised task for action recognition and predicts the final ten frames in a diagnostic experiment.","Recognition is primary; future pose is a parallel residual head evaluated mainly qualitatively.","This does not establish a standalone 30-frame future-pose predictor or anticipation-driven coaching benefit.","Use as related-task precedent only.","Standalone quantitative ACP errors, baseline comparison and downstream decision-effect evaluation.","https://arxiv.org/pdf/1904.12659"],
 ["E26","S12","pp. 1–4, Introduction and §3","Phase-model alternative","ASFormer combines temporal convolutions, hierarchical local-to-global attention and iterative decoders to refine framewise action-segmentation predictions.","Encoder plus successive decoders; tested on 50Salads, Breakfast and GTEA feature sequences.","Inputs are pre-extracted video features and minute-long activities, unlike 90-frame landmark jab windows.","Support local temporal priors and iterative refinement as alternative design choices.","Only compare after real labelled jab sessions exist and preserve grouped splits.","https://arxiv.org/pdf/2110.08568"],
 ["E27","S12","pp. 1–3, stated concerns","Small-data limitation","The paper argues that vanilla Transformer flexibility can be a liability with small action-segmentation training sets and that long sequences complicate attention learning.","Local connectivity constrains the hypothesis space; hierarchical attention reduces complexity.","The paper's 'small' public datasets remain far larger and more diverse than the current generated bootstrap set.","Support caution against adopting a high-capacity temporal model without real data.","Collect and annotate grouped real sessions before architecture selection or accuracy claims.","https://arxiv.org/pdf/2110.08568"],
 ["E28","S13","p. 1, Abstract","Dataset provenance","Human3.6M contains 3.6 million accurate 3D poses from 11 actors observed from four viewpoints with synchronized imagery, motion capture and depth-related data.","Five female and six male actors perform typical activities under controlled multiview capture.","Large frame count does not equal broad participant or domain diversity; the activities are not a jab-specific sample.","Document the origin and scale of a public motion benchmark used for offline research.","Keep public-benchmark evidence separate from P001 webcam evidence.","https://vision.imar.ro/human3.6m/human36m_techrep.pdf"],
 ["E29","S13","dataset/evaluation sections","Domain limitation","Human3.6M provides calibrated ground truth and controlled evaluation scenarios suited to algorithm comparison.","Multiple cameras, motion capture, time-of-flight data and body scans support accurate 3D labels.","Its physical calibration permits millimetre errors that normalized MediaPipe coordinates do not.","Support dataset-specific units and explicit domain-gap reporting.","Never relabel normalized ACP errors as millimetres without calibration.","https://vision.imar.ro/human3.6m/human36m_techrep.pdf"],
 ["E30","S14","pp. 1–2, Introduction","Dataset/uncertainty","Monocular 3D lifting is susceptible to depth ambiguity, while controlled 3D datasets may generalize poorly to clothing, pose, viewpoint and outdoor variation.","Single-RGB pose estimator combined with transfer from 2D data and a new markerless multiview dataset.","The estimator and benchmark are pose-estimation work, not future-pose or coaching evaluation.","Support monocular ambiguity and domain-generalization limitations.","Record occlusion/viewpoint failures in the P001 case.","https://arxiv.org/pdf/1611.09813"],
 ["E31","S14","pp. 5–6, §5","Dataset provenance","MPI-INF-3DHP records eight actors performing eight activity sets using markerless multiview capture, varied clothing and indoor/outdoor test conditions.","Four male and four female actors; green-screen studio plus appearance augmentation and outdoor/indoor benchmark sequences.","Eight actors and curated activities remain limited and do not represent jab technique diversity.","Support MPI-INF-3DHP provenance and its greater appearance/viewpoint diversity relative to controlled mocap.","Use as external offline evidence only and disclose technique/domain mismatch.","https://arxiv.org/pdf/1611.09813"],
 ["E32","S15","p. 1, Abstract","Sensor-fusion evidence","3DPW obtains accurate in-the-wild 3D poses by combining a moving camera with body-worn IMUs and enforcing 2D/3D consistency over time.","Method validated on TotalCapture; jointly optimizes body pose, camera pose and IMU heading drift.","Accuracy depends on wearable IMUs and optimization unavailable in the laptop-camera-only system.","Support sensor fusion as a future route to stronger ground truth.","Do not use 3DPW accuracy to imply current webcam accuracy.","https://openaccess.thecvf.com/content_ECCV_2018/papers/Timo_von_Marcard_Recovering_Accurate_3D_ECCV_2018_paper.pdf"],
 ["E33","S15","dataset description","Dataset provenance","3DPW contains more than 51,000 frames in challenging everyday sequences captured with a moving phone camera.","Video, IMU measurements, reconstructed 3D poses and body models are released for research.","Everyday activity coverage does not guarantee combat-sport motion coverage.","Support in-the-wild benchmark provenance and multimodal future-work rationale.","Jab-specific recordings and annotations remain necessary.","https://virtualhumans.mpi-inf.mpg.de/3DPW/"],
 ["E34","S16","pp. 1–2, Abstract and Introduction","Uncertainty","A single 2D observation can correspond to multiple feasible 3D poses because of depth ambiguity and occluded joints.","Normalizing-flow model generates multiple posterior hypotheses conditioned on 2D detections and their heatmap uncertainty.","Probabilistic hypotheses do not by themselves identify the physically correct pose.","Support uncertainty-aware interpretation of webcam-derived depth and angles.","Expose confidence/visibility and avoid overconfident feedback when evidence is weak.","https://arxiv.org/pdf/2107.13788"],
 ["E35","S16","pp. 4–7, method/evaluation","Evaluation boundary","The method evaluates ambiguity-aware hypotheses on Human3.6M and MPI-INF-3DHP, including a high-uncertainty subset.","Two-stage 2D-to-3D lifting; learned pose prior, heatmap-conditioned flow and best-of-M-style evaluation.","Results depend on benchmark detectors, annotations and sampling metrics unlike the deterministic MediaPipe pipeline.","Motivate an uncertainty/failure flag rather than transferred numerical performance.","Measure system behaviour by visibility/occlusion strata in real sessions.","https://arxiv.org/pdf/2107.13788"],
 ["E36","S20","pp. 2–3, Methods/Results","Jab biomechanics","Professional boxers showed higher wrist and elbow velocity than amateurs in selected maximal-velocity jab trials; no significant group differences were found for shoulder or centre-of-gravity velocity.","Four professional and five amateur male boxers; 2D 60 Hz camera, surface EMG, instrumented bag; fastest of three jabs selected.","Very small sample, selected-best trial, 2D capture and maximal bag striking limit generalization.","Support wrist/elbow sequencing as observable features, not fixed expert thresholds.","P001 frame annotation and explicit threshold provenance.","https://ojs.ub.uni-konstanz.de/cpa/article/view/3649/3430"],
 ["E37","S20","pp. 5–6, Discussion/limitations","Source limitation","The authors explicitly identify limited sample size, questionable high-range bag readings, selected-trial bias and protocol choices as limitations.","Conference proceedings study with exploratory correlations and training comparisons.","The evidence is insufficient for universal muscle-recruitment or force claims.","Use only as cautious multi-joint domain rationale.","Do not infer force from laptop-camera landmarks.","https://ojs.ub.uni-konstanz.de/cpa/article/view/3649/3430"],
 ["E38","S21","pp. 1–4, Abstract/Methods","Straight-punch biomechanics","The study compares multiple joint angles, angular velocities, punch time and distance between two right straight-punch stances using consumer video analysis.","Eight amateur boxers; iPhone at 60 FPS; Kinovea; researchers selected each participant's best attempt.","Right straight punch, stance definitions, small sample and best-attempt selection do not directly match a lead-jab webcam session.","Support feasibility of consumer-camera kinematic review and multi-joint variables.","Avoid transferring numerical thresholds; define the evaluated jab/stance precisely.","https://digitum.um.es/digitum/bitstream/10201/147517/1/The%20kinematic%20analysis%20of%20the%20straight%20punch%20in%20two%20ways%20for%20amateur.pdf"],
 ["E39","S21","pp. 6–10, Results/Conclusion","Domain evidence/limitation","Punch speed relationships differed by method; some shoulder, pelvis, knee, ankle and distance variables were non-significant while punch time and selected angular variables were associated with speed.","Within-sample correlations and between-method comparisons at alpha 0.05.","Small correlated-variable analysis cannot establish causal or universal correct-angle rules; wording in the paper is occasionally inconsistent.","Support context-dependent thresholds and reporting non-significant as well as significant results.","Expert review plus larger independent samples before prescriptive claims.","https://digitum.um.es/digitum/bitstream/10201/147517/1/The%20kinematic%20analysis%20of%20the%20straight%20punch%20in%20two%20ways%20for%20amateur.pdf"]
];

const csvEscape = (v) => `"${String(v ?? "").replaceAll('"','""')}"`;
await fs.writeFile(path.join(outputDir, "verified_literature_matrix.csv"), [headers, ...rows].map(r => r.map(csvEscape).join(",")).join("\r\n"), "utf8");

const wb = Workbook.create();
const summary = wb.worksheets.add("Review Summary");
const matrix = wb.worksheets.add("Literature Matrix");
const claims = wb.worksheets.add("Framework Claim Map");
const extraction = wb.worksheets.add("Evidence Extracts");
const gaps = wb.worksheets.add("Full Text Queue");
for (const s of [summary,matrix,claims,extraction,gaps]) { s.showGridLines = false; }

matrix.getRangeByIndexes(0,0,rows.length+1,headers.length).values = [headers,...rows];
matrix.tables.add(`A1:Q${rows.length+1}`, true, "LiteratureMatrixTable");
matrix.freezePanes.freezeRows(1); matrix.freezePanes.freezeColumns(3);
matrix.getRange("A1:Q1").format = {fill:"#123047",font:{bold:true,color:"#FFFFFF"},wrapText:true,verticalAlignment:"center"};
matrix.getRange(`A2:Q${rows.length+1}`).format = {font:{size:9,color:"#172B3A"},verticalAlignment:"top",wrapText:true};
matrix.getRange(`C2:C${rows.length+1}`).format.numberFormat = "0";
const widths = [11,20,8,38,24,23,30,38,28,48,48,44,24,26,60,34,24];
widths.forEach((w,i)=>matrix.getRangeByIndexes(0,i,rows.length+1,1).format.columnWidth=w);
matrix.getRange("1:1").format.rowHeight = 34;

summary.getRange("A1:H1").merge(); summary.getRange("A1").values=[["Combat Cognition — Verified Literature Matrix v4"]];
summary.getRange("A2:H2").merge(); summary.getRange("A2").values=[["Core source set for framework evaluation and claim control. This is not thesis prose."]];
summary.getRange("A4:B8").values=[["Review date",new Date(2026,7,1)],["Total sources",null],["Included / cautious",null],["Direct-support exclusions",null],["Full-text status","21 included sources extracted for selected claims; queue closed."]];
summary.getRange("B4").format.numberFormat="yyyy-mm-dd";
summary.getRange("B5").formulas=[[`=COUNTA('Literature Matrix'!$A$2:$A$${rows.length+1})`]];
summary.getRange("B6").formulas=[[`=COUNTIF('Literature Matrix'!$Q$2:$Q$${rows.length+1},"Include")+COUNTIF('Literature Matrix'!$Q$2:$Q$${rows.length+1},"Include with caution")`]];
summary.getRange("B7").formulas=[[`=COUNTIF('Literature Matrix'!$Q$2:$Q$${rows.length+1},"Exclude from direct support")`]];
summary.getRange("A10:H10").values=[["Scope control","What this matrix supports","What it does not support","Current empirical boundary","Operational reasoning","Human evaluation","Video handling","Next review gate"]];
summary.getRange("A11:H11").values=[["Jab only; P001; laptop camera","Architecture rationale, metric selection, limitations and methodological framing","Population effectiveness, universal martial-arts correctness, human-equivalent cognition or calibrated 3D biomechanics","Single-participant expert feasibility/self-evaluation plus generated-data model checks","Deterministic rule/template output; no operational OpenAI LLM found","P001 self-validation; no independent expert","Private and excluded from report","Reconcile the closed literature register against local evidence and unresolved evaluation actions"]];
summary.getRange("A1:H1").format={fill:"#123047",font:{bold:true,color:"#FFFFFF",size:16},horizontalAlignment:"left",verticalAlignment:"center"};
summary.getRange("A2:H2").format={fill:"#DCEAF2",font:{italic:true,color:"#35566B"}};
summary.getRange("A4:A8").format={fill:"#EAF2F6",font:{bold:true,color:"#123047"}};
summary.getRange("A10:H10").format={fill:"#2D6A78",font:{bold:true,color:"#FFFFFF"},wrapText:true};
summary.getRange("A11:H11").format={fill:"#F4F8FA",font:{color:"#172B3A"},wrapText:true,verticalAlignment:"top"};
summary.getRange("A1:H11").format.borders={preset:"outside",style:"thin",color:"#9FB8C5"};
summary.getRange("A1:H11").format.columnWidth=22; summary.getRange("B4:B8").format.columnWidth=48;
summary.getRange("1:1").format.rowHeight=30; summary.getRange("2:2").format.rowHeight=24; summary.getRange("10:10").format.rowHeight=32; summary.getRange("11:11").format.rowHeight=88;

const claimRows = [
 ["C01","Laptop-camera landmark perception is technically feasible","S01; S02; S03; S04","Implemented software verification plus screenshots","Do not convert feasibility into application accuracy"],
 ["C02","Skeleton sequences can be represented with spatial-temporal graphs","S05; S06; S07; S10","ACP-STGAT architecture and generated-data pipeline checks","External recognition studies do not validate this predictor"],
 ["C03","Future-pose evaluation needs simple baselines and horizon-specific errors","S08; S09","Normalized MPJPE/ADE/FDE and per-horizon evidence","No millimetre claim without physical calibration"],
 ["C04","Ordered movement requires temporal/segment evaluation beyond frame accuracy","S11; S12","Accuracy, balanced accuracy, macro/per-class F1, confusion matrix; boundary work pending","Current phase results are generated bootstrap evidence"],
 ["C05","Monocular 3D evidence is uncertain and domain-dependent","S13; S14; S15; S16","Laptop-camera-only P001 case and documented limitations","No calibrated 3D biomechanics or universal angle thresholds"],
 ["C06","Situation awareness is a conceptual lens for perception-comprehension-projection","S17","L1-L4 state, ACP projection and context packet","Do not claim human awareness or complete cognition"],
 ["C07","Artifact evaluation fits an expert-informed design-science case","S18","Tests, model checks, framework case, failure modes and reflexive disclosure","Researcher self-review remains biased and non-independent"],
 ["C08","Jab performance is multi-joint and context dependent","S19; S20; S21","Expert feedback traces involving elbow, shoulder and guard","Do not infer fixed universal thresholds from small/heterogeneous studies"],
 ["C09","STGAT name similarity is not task equivalence","S22","Terminology/exclusion log","Pedestrian trajectory results cannot validate articulated pose prediction"]
];
claims.getRangeByIndexes(0,0,claimRows.length+1,5).values=[["claim_id","controlled_framework_claim","supporting_sources","local_evidence_needed","mandatory_boundary"],...claimRows];
claims.tables.add(`A1:E${claimRows.length+1}`,true,"ClaimMapTable"); claims.freezePanes.freezeRows(1);
claims.getRange("A1:E1").format={fill:"#123047",font:{bold:true,color:"#FFFFFF"},wrapText:true};
claims.getRange(`A2:E${claimRows.length+1}`).format={wrapText:true,verticalAlignment:"top",font:{size:10,color:"#172B3A"}};
[12,44,22,44,48].forEach((w,i)=>claims.getRangeByIndexes(0,i,claimRows.length+1,1).format.columnWidth=w);

extraction.getRangeByIndexes(0,0,extractionRows.length+1,extractionHeaders.length).values=[extractionHeaders,...extractionRows];
extraction.tables.add(`A1:J${extractionRows.length+1}`,true,"EvidenceExtractsTable"); extraction.freezePanes.freezeRows(1); extraction.freezePanes.freezeColumns(2);
extraction.getRange("A1:J1").format={fill:"#244F62",font:{bold:true,color:"#FFFFFF"},wrapText:true};
extraction.getRange(`A2:J${extractionRows.length+1}`).format={wrapText:true,verticalAlignment:"top",font:{size:9,color:"#172B3A"}};
[11,10,24,19,52,42,45,46,42,58].forEach((w,i)=>extraction.getRangeByIndexes(0,i,extractionRows.length+1,1).format.columnWidth=w);

const pendingRows = rows.filter(r=>!String(r[16]).startsWith("Exclude") && !fullyExtracted.has(r[0])).map((r,i)=>[i<5?"High":i<10?"Medium":"Low",r[0],r[3],r[12],"Full-text analytic extraction pending","Capture exact page/section, method, sample, measures, limitations and one paraphrased supported proposition"]);
const queueRows = pendingRows.length ? pendingRows : [["Closed","—","No included sources remain in this core queue","All","Complete","Re-open only when a new framework claim requires additional literature"]];
gaps.getRangeByIndexes(0,0,queueRows.length+1,6).values=[["priority","source_id","title","planned_section","status","next_action"],...queueRows];
gaps.tables.add(`A1:F${queueRows.length+1}`,true,"FullTextQueueTable"); gaps.freezePanes.freezeRows(1);
gaps.getRange("A1:F1").format={fill:"#7A4E12",font:{bold:true,color:"#FFFFFF"},wrapText:true};
gaps.getRange(`A2:F${queueRows.length+1}`).format={wrapText:true,verticalAlignment:"top",font:{size:10,color:"#172B3A"}};
[12,12,46,26,30,58].forEach((w,i)=>gaps.getRangeByIndexes(0,i,queueRows.length+1,1).format.columnWidth=w);

const errorScan = await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A",options:{useRegex:true,maxResults:100},summary:"formula error scan"});
console.log(errorScan.ndjson);
for (const [sheetName,range,fileName] of [["Review Summary","A1:H11","review_summary.png"],["Literature Matrix","A1:Q8","literature_matrix.png"],["Framework Claim Map",`A1:E${claimRows.length+1}`,"claim_map.png"],["Evidence Extracts","A1:J8","evidence_extracts.png"],["Full Text Queue","A1:F10","full_text_queue.png"]]) {
  const preview=await wb.render({sheetName,range,scale:1.2,format:"png"});
  await fs.writeFile(path.join(outputDir,fileName),new Uint8Array(await preview.arrayBuffer()));
}
const xlsx=await SpreadsheetFile.exportXlsx(wb);
await xlsx.save(path.join(outputDir,"Combat_Cognition_Verified_Literature_Matrix_v4.xlsx"));
console.log((await wb.inspect({kind:"table",range:"Review Summary!A1:H11",include:"values,formulas",tableMaxRows:15,tableMaxCols:10})).ndjson);
